version: 0.1

phases:
  pre_build:
    commands:
      - df -h
      # Fix codepipeline's shit ability to maintain permissions
      - chmod +x ./archiso/mkarchiso
      - chmod +x ./configs/baseline/build.sh
      - chmod +x ./configs/releng/airootfs/etc/systemd/scripts/choose-mirror
      - chmod +x ./configs/releng/airootfs/root/.automated_script.sh
      - chmod +x ./configs/releng/airootfs/root/.mount_packages.sh
      - chmod +x ./configs/releng/airootfs/root/customize_airootfs.sh
      - chmod +x ./configs/releng/build.sh
      - chmod +x ./create-executable-list
      - chmod +x ./update-arch-iso.sh
  build:
    commands:
      - bash -x ./update-arch-iso.sh

artifacts:
  files:
    - '*.iso'
  discard-paths: yes
