#!/bin/bash

# This is a hacky workaround for codebuild destroying all permissions on files in a git repo.

find . -executable -type f | grep -v '\.git' | while read i; do
	echo "      - chmod +x $i"
done
